name: sage
description: "An AI doctor assistant"

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  chat_gpt_sdk: ^3.1.0
  flutter:
    sdk: flutter
  flutter_displaymode: ^0.6.0
  flutter_localizations:
    sdk: flutter
  google_generative_ai: ^0.4.6
  hooks_riverpod: ^2.5.2
  realm: ^20.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
